export const CREATE_EDITING_SETTING = 'CREATE_EDITING_SETTING';
export const UPDATE_DISTANCE = 'UPDATE_DISTANCE';
export const UPDATE_SORT_BY = 'UPDATE_SORT_BY';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';